device: cpu
train:
  batch_size: 128
  train_epochs: 1000
  loss:
    - mseloss
  optim:
    name: adam
    learning_rate: 0.0001
    others: 
  max_eps: 0.9
  min_eps: 0.1
  eps_decay: 200
  discount_factor: 0.99
  target_update_period: 100
  target_update_ratio: 0.01
  memory_length: 10000
  model_path: ./pretrained
  progress_path: ./train_progress
  plot_epochs: 50
model:
  architecture:
    - Conv2d:
        args: [4, 16]
        kernel_size: 5
        stride: 2
    - BatchNorm2d:
        args: [16]
    - ReLU:
    - Conv2d:
        args: [16, 32]
        kernel_size: 5
        stride: 2
    - BatchNorm2d:
        args: [32]
    - ReLU:
    - Conv2d:
        args: [32, 32]
        kernel_size: 5
        stride: 2
    - BatchNorm2d:
        args: [32]
    - ReLU:
    - AdaptiveAvgPool2d:
        args: [4]
    - Flatten:
    - Linear:
        args: [512, 4]
env:
  name: Breakout

